spring.application.name=gitdemo
# ✅ DATASOURCE (Neon)
spring.datasource.url=jdbc:postgresql://ep-aged-mouse-anc3r8z4.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Ai6j9XkKHhfg

# ✅ JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ✅ HIKARI (VERY IMPORTANT FOR CLOUD DB)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.keepalive-time=15000
spring.datasource.hikari.validation-timeout=5000

# ✅ SSL (REQUIRED FOR NEON)
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

